### ISSUE TITLE
怎么使用？

### ISSUE THREAD

**Issue by KumaNNN** [SpiritLingPub/hexo-images-watermark#10]
怎么使用？ 配置中的参数项有点少或者说有点模糊，有没有完整的啊？
```
watermark:
    enable: true
    textEnable: true
    rotate: -45
    gravity: centre
```

**Comment by SpiritLing** [comment]
https://github.com/SpiritLingPub/hexo-images-watermark#%E5%8F%82%E6%95%B0
README.md中是存在参数详细的，所有参数是平铺的，只有一级。
```
watermark:
    enable: true
    textEnable: true
    imageEnable: false
    static: true
    dynamic: true
    log: true
    rotate: -45
    gravity: centre
```
只要按照参数写就行，我自己使用的就是
```
watermark:
    enable: true
    textEnable: true
    rotate: -45
    gravity: centre
```
