### ISSUE TITLE
已经正确安装且配置文件也已修改 但仍无法添加水印

### ISSUE THREAD

**Issue by jmb0217** [SpiritLingPub/hexo-images-watermark#42]

**Comment by hansenz42** [comment]
实测可以用，你看下 generate 之后的 public 文件夹，如果用 Next 主题，生成的文件夹不是 posts ，要手动加文件夹：
```yaml
watermark:
  enable: true
  textEnable: true
  directory:
    - 2023
    - 2024
```
